import{a as m,S as p,i as a}from"./assets/vendor-tnUJPedx.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const y="48548888-6a688bae8a9a8d1a3f9b35105",g="https://pixabay.com/api/";async function h(o){try{return(await m.get(g,{params:{key:y,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data.hits}catch(t){return console.error("The field is empty",t),[]}}function b(o,t){t.innerHTML=o.map(({webformatURL:n,largeImageURL:e,tags:r,likes:i,views:u,comments:f,downloads:d})=>`
      <a href="${e}" class="gallery-item">
        <img src="${n}" alt="${r}" />
        <div class="info">
          <p>❤️ ${i} | 👀 ${u} | 💬 ${f} | ⬇️ ${d}</p>
        </div>
      </a>
    `).join(""),new p(".gallery a").refresh()}const L=document.querySelector("#search-form"),c=document.querySelector(".gallery"),l=document.querySelector(".loader");L.addEventListener("submit",async o=>{o.preventDefault();const t=o.target.elements.searchQuery.value.trim();if(!t){a.error({title:"Error",message:"The field is empty!"});return}c.innerHTML="",l.style.display="block";const s=await h(t);if(l.style.display="none",s.length===0){a.warning({title:"Error",message:"Please try again!"});return}b(s,c)});
//# sourceMappingURL=index.js.map
